name: CI
# controle le declenchement de workflow
on:
push:
   branches: [ main ]
# on peut ajouter d'autres branches exemple dev branches [main,dev]   
pull_request:
   branches: [ main ]
# nous permet d'executer ce workflow manuellement a partir de l'onglet actions
workflow_dispatch:
# le workflow d'un ou plusisuers jobs qui peuvent etre executés sequentiellement ou en parallel 
jobs:
# ce workflow contient un single job nommé 'build'
   build:
     # machine ou vm sur le quel on va executer le job on peut ajouter d'Autre machines comme ubuntu-latest
     runs-on: windows-latest
     steps:
          # verifie si le job peut acceder a votre workspace $github_Workspace
          -  uses: actions/checkout@v3
          -  name: Run a one-line script
            run: echo hello word
          - name: Run a multi-line script
            run: |
               echo add other actions to build
               echo tester, et deployer le projet
